name: CLI Compiler Tag Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release-draft:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev cmake build-essential

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Compress CLI Binary
      run: |
        cd build
        tar -czf ../spm-cli-linux-${{ github.ref_name }}.tar.gz spm
        cd ..

    - name: Create GitHub Release Draft
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: spm-cli-linux-${{ github.ref_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
