name: CLI Compiler Release CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install C++ dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev cmake build-essential

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build C++ Binary
      run: cmake --build build --config Release

    - name: Structure Release Artifacts
      run: |
        mkdir -p release_dist
        cp build/spm release_dist/spm

    - name: Deploy to release-cli Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release_dist
        branch: release-cli
        target-folder: .
        clean: true
